---
title: "PM566 Lab03"
author: "Wenjia Lu"
format: 
  html:
    embed-resources: true
---

```{r}
## Step 1.Read in the data ##

library(utils)
download.file(
  "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
  destfile = file.path("met_all.gz"),
  method   = "libcurl",
  timeout  = 60
)

met <- data.table::fread(file.path("met_all.gz"))

```


```{r}
## Step 2.Check the dimensions, headers, footers ##

dim(met)
nrow(met)
ncol(met)
head(met)
tail(met)      

#2,377,343 rows and 30 cols in the met dataset
```


```{r}
## Step 3.Take a look at the variables ##

str(met)
```


```{r}
## Step 4.Take a closer look at the key variables ##

table(met$year)
table(met$day)
table(met$hour)

summary(met$temp)
summary(met$elev)  # has obs with 9999.0, an indicator for missing
summary(met$wind.sp)  # too many missing data

met[met$elev==9999.0] <- NA  # repalce 9999 as NA
summary(met$elev)

mean(is.na(met$temp))
met <- met[temp>-40]  # remove -40C
met2 <- met[order(temp)]
head(met2)  # -17.2C temperature seems suspicious

```


```{r}
## Step 5.Check the data against an external data source ##

met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)  # removed temperatures colder than -15C.

```


```{r}
## Step 6. Calculate summary statistics ##

elev <- met[elev==max(elev)]
summary(elev)

cor(elev$temp, elev$wind.sp, use="complete")
cor(elev$temp, elev$hour, use="complete")
cor(elev$wind.sp, elev$day, use="complete")
cor(elev$wind.sp, elev$hour, use="complete")
cor(elev$temp, elev$day, use="complete")

```


```{r}
## Step 7. Exploratory graphs ##

hist(met$elev, breaks=100)
hist(met$temp)
hist(met$wind.sp)

library(tidyverse)
library(leaflet)
leaflet(elev) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat =~ lat,lng =~ lon, opacity = 1, fillOpacity = 1, radius = 100)

library(lubridate)
elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' '))) # create a date-time variable
summary(elev$date)
elev <- elev[order(date)]
head(elev)

plot(elev$date, elev$temp, type='l')
plot(elev$date, elev$wind.sp, type='l')

```


```{r}
## Step 8.Further explorations ##

# the relationship between temp and rh for day=20.
library(ggplot2)
met3<-met[day==20]
ggplot(data = met3, mapping = aes(x = temp, y = rh)) +geom_point() + geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Temperature and rh", xlab  = "temp", y = "rh")

# scatter plots between temp, lat, rh.
pairs(~ temp + lat + rh, data = met3)

```